site_name: SCRCR - Guía de Usuario
theme:
  name: material
  logo: images/logo.webp
  language: es

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Acceso al Sistema: acceso.md
  - Roles de Usuario: roles.md
  - Menú Principal: dashboard.md
  - Listado de Asociados: asociados.md
  - Congregados: congregados.md
  - Eventos: eventos.md
  - Gestión de Usuarios: usuarios.md
  - Planilla: planilla.md
  - Reportes: reportes.md
  - Permisos: permisos.md
  - Actas: actas.md
  - Configuración: configuracion.md
  - Recomendaciones: recomendaciones.md